<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-08-13 01:23:24',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-09-06 06:52:44',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-08-13 01:23:24',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-08-13 01:23:24',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-09-06 06:56:37',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-09-06 06:52:49',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-08-13 01:23:24',
                'updated_at' => '2019-09-06 06:52:50',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2019-08-13 01:23:25',
                'updated_at' => '2019-09-06 06:52:50',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2019-08-13 01:23:25',
                'updated_at' => '2019-09-06 06:52:51',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2019-08-13 01:23:25',
                'updated_at' => '2019-09-06 06:56:41',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2019-08-13 01:23:27',
                'updated_at' => '2019-09-06 06:56:37',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2019-08-13 01:23:28',
                'updated_at' => '2019-08-13 01:23:28',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2019-08-13 01:23:29',
                'updated_at' => '2019-08-13 01:23:29',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => 'Plans',
                'url' => '/products',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-08-18 23:20:08',
                'updated_at' => '2019-09-03 00:06:06',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Just for You',
                'url' => 'site/offers',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-08-18 23:54:21',
                'updated_at' => '2019-09-16 08:25:20',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'XOX Fast/Payment',
                'url' => '/site/rewards',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-18 23:54:44',
                'updated_at' => '2019-09-16 08:25:21',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => 'Support',
                'url' => '/support',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-08-18 23:55:22',
                'updated_at' => '2019-09-16 08:25:22',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 19,
                'menu_id' => 3,
                'title' => 'Why us',
                'url' => 'site/why_us',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2019-08-19 03:11:05',
                'updated_at' => '2019-08-19 03:11:05',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 20,
                'menu_id' => 3,
                'title' => 'Board of directors',
                'url' => '/site/board_of_directors',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2019-08-19 03:11:33',
                'updated_at' => '2019-08-19 03:11:33',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 21,
                'menu_id' => 3,
                'title' => 'Corporate Information',
                'url' => '/site/corporate/information',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2019-08-19 03:12:02',
                'updated_at' => '2019-08-19 03:12:02',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 22,
                'menu_id' => 3,
                'title' => 'Investor Relations',
                'url' => '/site/investor/relations',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2019-08-19 03:12:33',
                'updated_at' => '2019-08-19 03:12:33',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 23,
                'menu_id' => 4,
                'title' => 'XOX Self-Care',
                'url' => 'https://selfcare.xox.com.my',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2019-08-19 03:14:26',
                'updated_at' => '2019-09-02 23:01:10',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 24,
                'menu_id' => 4,
                'title' => 'Online Store',
                'url' => 'https://xox.com.my/onlinestore/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2019-08-19 03:15:06',
                'updated_at' => '2019-08-19 03:15:06',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 25,
                'menu_id' => 5,
                'title' => 'Quick Help',
                'url' => '/site/quick/help',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 21,
                'created_at' => '2019-08-19 03:16:07',
                'updated_at' => '2019-08-19 03:16:07',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 26,
                'menu_id' => 5,
                'title' => 'FAQ',
                'url' => '/site/faq',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 22,
                'created_at' => '2019-08-19 03:16:25',
                'updated_at' => '2019-08-19 03:16:25',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 27,
                'menu_id' => 5,
                'title' => 'User Guide',
                'url' => '/site/user/guide',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 23,
                'created_at' => '2019-08-19 03:16:46',
                'updated_at' => '2019-08-19 03:16:46',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 28,
                'menu_id' => 6,
                'title' => 'Blog',
                'url' => '/blog',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-26 13:40:28',
                'updated_at' => '2019-08-26 13:40:28',
                'route' => NULL,
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Blog',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-08-26 13:40:28',
                'updated_at' => '2019-08-26 13:40:28',
                'route' => NULL,
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 1,
                'created_at' => '2019-08-26 13:40:28',
                'updated_at' => '2019-08-26 13:40:28',
                'route' => 'voyager.blog_posts.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 2,
                'created_at' => '2019-08-26 13:40:28',
                'updated_at' => '2019-08-26 13:40:28',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'menu_id' => 6,
                'title' => 'Home',
                'url' => '/home',
                'target' => '_self',
                'icon_class' => '',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'menu_id' => 6,
                'title' => 'About',
                'url' => '/about',
                'target' => '_self',
                'icon_class' => '',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'menu_id' => 6,
                'title' => 'Contact',
                'url' => '/contact',
                'target' => '_self',
                'icon_class' => '',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'menu_id' => 7,
                'title' => 'Facebook',
                'url' => 'https://www.facebook.com/wearepvtl',
                'target' => '_blank',
                'icon_class' => 'fa-facebook-square',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'menu_id' => 7,
                'title' => 'Twitter',
                'url' => 'https://twitter.com/wearepvtl',
                'target' => '_blank',
                'icon_class' => 'fa-twitter-square',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'menu_id' => 7,
                'title' => 'Instagram',
                'url' => 'https://www.instagram.com/wearepvtl/',
                'target' => '_blank',
                'icon_class' => 'fa-instagram',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'menu_id' => 7,
                'title' => 'Google+',
                'url' => 'https://plus.google.com/100970850483584616344',
                'target' => '_blank',
                'icon_class' => 'fa-google-plus-square',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'menu_id' => 7,
                'title' => 'LinkedIn',
                'url' => 'https://www.linkedin.com/company/pivotal-agency',
                'target' => '_blank',
                'icon_class' => 'fa-linkedin',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-08-26 13:40:38',
                'updated_at' => '2019-08-26 13:40:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'menu_id' => 8,
                'title' => 'ONEXOX Black',
                'url' => '/onexox-black',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-08-28 13:55:28',
                'updated_at' => '2019-09-02 22:58:10',
                'route' => NULL,
                'parameters' => '',
            ),
            39 => 
            array (
                'id' => 41,
                'menu_id' => 8,
                'title' => 'ONEXOX Offer',
                'url' => '/onexox-offer',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-08-28 13:55:55',
                'updated_at' => '2019-09-02 22:58:33',
                'route' => NULL,
                'parameters' => '',
            ),
            40 => 
            array (
                'id' => 42,
                'menu_id' => 8,
                'title' => 'TKKR',
                'url' => '/tkkr',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-28 13:56:19',
                'updated_at' => '2019-09-02 22:58:12',
                'route' => NULL,
                'parameters' => '',
            ),
            41 => 
            array (
                'id' => 43,
                'menu_id' => 8,
                'title' => 'eSIM',
                'url' => '/esim',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-08-28 13:56:43',
                'updated_at' => '2019-09-02 22:58:12',
                'route' => NULL,
                'parameters' => '',
            ),
            42 => 
            array (
                'id' => 45,
                'menu_id' => 1,
                'title' => 'Terms & Condition Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-09-06 03:53:20',
                'updated_at' => '2019-09-06 06:56:36',
                'route' => 'voyager.terms-condition-categories.index',
                'parameters' => NULL,
            ),
            43 => 
            array (
                'id' => 46,
                'menu_id' => 1,
                'title' => 'Faq Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 48,
                'order' => 1,
                'created_at' => '2019-09-06 06:31:39',
                'updated_at' => '2019-09-06 07:00:17',
                'route' => 'voyager.faq-categories.index',
                'parameters' => 'null',
            ),
            44 => 
            array (
                'id' => 47,
                'menu_id' => 1,
                'title' => 'Faq Details',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-info-circled',
                'color' => NULL,
                'parent_id' => 48,
                'order' => 2,
                'created_at' => '2019-09-06 06:45:31',
                'updated_at' => '2019-09-06 06:54:06',
                'route' => 'voyager.faq-details.index',
                'parameters' => NULL,
            ),
            45 => 
            array (
                'id' => 48,
                'menu_id' => 1,
                'title' => 'FAQ',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-info-circled',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-09-06 06:52:34',
                'updated_at' => '2019-09-06 06:56:22',
                'route' => NULL,
                'parameters' => '',
            ),
            46 => 
            array (
                'id' => 49,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2019-09-17 08:43:37',
                'updated_at' => '2019-09-17 08:43:37',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}